In [ ]:
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.

In [7]:
import numpy as np
a=np.arange(10,51)
print(a)

b=np.random.rand(3,3)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.98822212 0.29753839 0.85571477]
 [0.73197747 0.26206291 0.74452884]
 [0.14684813 0.12708706 0.49971727]]


In [ ]:
Find the shape, size, and data type of the array you created in the previous task.

In [11]:
print(b.shape)
print(b.size)
print(b.dtype)

(3, 3)
9
float64


In [ ]:
Add 5 to every element of a 1D array
Multiply two 2D arrays element-wise.

In [23]:
print(a+5)
m1 = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8]])
m2 = np.array([[3, 2, 1], [6, 4, 5], [0, 9, 8]])
print(m1*m2)


[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[ 3  4  3]
 [24 20 30]
 [ 0 63 64]]


In [ ]:
◦ Create a 5x5 array of integers from 1 to 25. Extract:
▪ The first row.
▪ The last column.
▪ A subarray of the first three rows and first two columns.

In [52]:
m3=np.arange(1,26).reshape(5,5)
print(m3)
print(m3[0])
print(m3[:,-1])
sub_arr=(m3[:3,:2])
print(sub_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]


In [ ]:
◦ Create a 10-element array of random integers between 1 and 100. Find:
▪ The maximum value.
▪ The minimum value.
▪ The mean and standard deviation.

In [66]:
a=np.arange(1,101)
print(a)
print(a.max())
print(a.min())
print(a.mean())
print(a.std())

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
100
1
50.5
28.86607004772212


In [ ]:
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.

In [68]:
a=np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.

In [74]:
m1=np.ones((3,3))
print(m1)
m2=np.array([1,2,3])
m3=m1+m2
print(m3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [ ]:
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.

In [88]:
m1=np.arange(1,51)
print(m3)
m2=m1[m1%5==0]
print(m2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[ 5 10 15 20 25 30 35 40 45 50]


In [ ]:
Create two 2x2 matrices and perform matrix multiplication.

In [90]:
m1 = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8]])
m2 = np.array([[3, 2, 1], [6, 4, 5], [0, 9, 8]])
m3=np.dot(m1,m2)
print(m3)

[[ 15  37  35]
 [ 42  82  77]
 [ 60 112 105]]


In [ ]:
Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [ ]:
m1 = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8],[0,1,2]])
m=m1[np.arange(4),np.arange(4)]